os: linux
dist: focal
vm:
  size: x-large
language: generic
addons:
  apt:
    packages:
      - libxml-xpath-perl
services:
  - docker

git:
  depth: false

env:
  global:
    # Separate branches by space
    - PROD_RELEASE_BRANCHES='master'
    - NODE_VERSION="v16"
    - TEST_CMD="./run_sc_tests.sh"
    - API_ZEN_REPO_URL="https://api.github.com/repos/HorizenOfficial/zen"

before_script:
  - source ci/setup_env.sh
  - ci/travis_keep_alive.sh

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/zen_release

.com.github.horizenofficial.sidechain-sdk.job-definitions:
  - &test_docker_amd64_x-large
    if: NOT env(SKIP_TESTS)
    os: linux
    dist: focal
    vm:
      size: x-large
    script:
      - bash -c "chmod +x ${TRAVIS_BUILD_DIR}/ci/run_python_tests.sh"
      - bash -c "${TRAVIS_BUILD_DIR}/ci/run_python_tests.sh ${TEST_CMD} ${TEST_ARGS} ${NODE_VERSION}"

if: branch = main OR tag IS present

jobs:
  fast_finish: true
  include:
    - stage: Test
      <<: *test_docker_amd64_x-large
      env:
        - TEST_ARGS="-split=9:1"
    - stage: Test
      <<: *test_docker_amd64_x-large
      env:
        - TEST_ARGS="-split=9:2"
    - stage: Test
      <<: *test_docker_amd64_x-large
      env:
        - TEST_ARGS="-split=9:3"
    - stage: Test
      <<: *test_docker_amd64_x-large
      env:
        - TEST_ARGS="-split=9:4"
    - stage: Test
      <<: *test_docker_amd64_x-large
      env:
        - TEST_ARGS="-split=9:5"
    - stage: Test
      <<: *test_docker_amd64_x-large
      env:
        - TEST_ARGS="-split=9:6"
    - stage: Test
      <<: *test_docker_amd64_x-large
      env:
        - TEST_ARGS="-split=9:7"
    - stage: Test
      <<: *test_docker_amd64_x-large
      env:
        - TEST_ARGS="-split=9:8"
    - stage: Test
      <<: *test_docker_amd64_x-large
      env:
        - TEST_ARGS="-split=9:9"
    - stage: java project
      name: jdk-11_latest
      script: ci/script.sh
      env:
      - TESTS_DOCKER_ORG='zencash'
      - TESTS_IMAGE_NAME='sc-ci-base'
      - TESTS_IMAGE_TAG='focal_jdk-11_latest'
      - TESTS='000'

deploy:
  provider: releases
  token: $GH_TOKEN_RELEASES
  prerelease: $IS_A_GH_PRERELEASE
  overwrite: true
  on:
    tags: true
    condition: $IS_A_RELEASE = true